package com.zenbyte.leave.controller;
import com.zenbyte.leave.dto.*; import com.zenbyte.leave.entity.*; import com.zenbyte.leave.service.*; import jakarta.validation.Valid; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController public class LeaveController {
 private final LeaveService s; private final AuthenticationService auth; public LeaveController(LeaveService s,AuthenticationService auth){this.s=s;this.auth=auth;}
 @PostMapping("/api/user/leaves") public Map<String,Object> create(@Valid @RequestBody LeaveCreateRequest r){LeaveRequest l=s.create(auth.current().getEmployee().getId(),r);return map(l);}
 @GetMapping("/api/user/leaves") public List<Map<String,Object>> mine(@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to){LocalDate f=from==null?LocalDate.now().minusYears(1):from,t=to==null?LocalDate.now().plusYears(1):to;return s.my(auth.current().getEmployee().getId(),f,t).stream().map(this::map).toList();}
 @GetMapping("/api/admin/leaves") public List<Map<String,Object>> admin(@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to,@RequestParam(required=false) String search,@RequestParam(required=false) LeaveStatus status){LocalDate f=from==null?LocalDate.now().withDayOfMonth(1):from,t=to==null?LocalDate.now().withDayOfMonth(1).plusMonths(1).minusDays(1):to;return s.admin(f,t,search,status).stream().map(this::map).toList();}
 @PutMapping("/api/admin/leaves/{id}/status") public Map<String,Object> action(@PathVariable Long id,@Valid @RequestBody LeaveActionRequest r){return map(s.action(id,r));}
 @DeleteMapping("/api/admin/leaves/{id}") public void delete(@PathVariable Long id){s.delete(id);}
 private Map<String,Object> map(LeaveRequest l){Map<String,Object> m=new LinkedHashMap<>();m.put("id",l.getId());m.put("employeeId",l.getEmployee().getId());m.put("employeeCode",l.getEmployee().getEmployeeId());m.put("employeeName",l.getEmployee().getName());m.put("fromDate",l.getFromDate());m.put("toDate",l.getToDate());m.put("leaveDays",l.getLeaveDays());m.put("reason",l.getReason());m.put("description",l.getDescription());m.put("status",l.getStatus());m.put("appliedDate",l.getAppliedDate());m.put("actionDate",l.getActionDate());m.put("adminRemarks",l.getAdminRemarks());return m;}
}
